use crate::paramstruct;

paramstruct! {
    Bsim4Inst,
    "BSIM4 Instance Parameters",[
    (l, f64, "Length"),
    (w, f64, "Width"),
    (nf, f64, "Number of fingers"),
    (sa, f64, "distance between  OD edge to poly of one side "),
    (sb, f64, "distance between  OD edge to poly of the other side"),
    (sd, f64, "distance between neighbour fingers"),
    (sca, f64, "Integral of the first distribution function for scattered well dopant"),
    (scb, f64, "Integral of the second distribution function for scattered well dopant"),
    (scc, f64, "Integral of the third distribution function for scattered well dopant"),
    (sc, f64, "Distance to a single well edge "),
    (min, usize, "Minimize either D or S"),
    (ad, f64, "Drain area"),
    (r#as, f64, "Source area"), // Note `r#as` allows the keyword `as`
    (pd, f64, "Drain perimeter"),
    (ps, f64, "Source perimeter"),
    (nrd, f64, "Number of squares in drain"),
    (nrs, f64, "Number of squares in source"),
    (off, bool, "Device is initially off"),
    (rbdb, f64, "Body resistance"),
    (rbsb, f64, "Body resistance"),
    (rbpb, f64, "Body resistance"),
    (rbps, f64, "Body resistance"),
    (rbpd, f64, "Body resistance"),
    (delvto, f64, "Zero bias threshold voltage variation"),
    (xgw, f64, "Distance from gate contact center to device edge"),
    (ngcon, f64, "Number of gate contacts"),
    (trnqsmod, usize, "Transient NQS model selector"),
    (acnqsmod, usize, "AC NQS model selector"),
    (rbodymod, usize, "Distributed body R model selector"),
    (rgatemod, usize, "Gate resistance model selector"),
    (geomod, usize, "Geometry dependent parasitics model selector"),
    (rgeomod, usize, "S/D resistance and contact model selector"),
    // Unsupported:
    // (ic, Vec<f64>, "Vector of DS,GS,BS initial voltages"),
    ]
}
paramstruct! {
    Bsim4OpPoint,
    "BSIM4 Operating Point",[
        (gmbs, f64, "Gmb"),
        (gm, f64, "Gm"),
        (gds, f64, "Gds"),
        (vdsat, f64, "Vdsat"),
        (vth, f64, "Vth"),
        (id, f64, "Ids"),
        (ibd, f64, "Ibd"),
        (ibs, f64, "Ibs"),
        (gbd, f64, "gbd"),
        (gbs, f64, "gbs"),
        (isub, f64, "Isub"),
        (igidl, f64, "Igidl"),
        (igisl, f64, "Igisl"),
        (igs, f64, "Igs"),
        (igd, f64, "Igd"),
        (igb, f64, "Igb"),
        (igcs, f64, "Igcs"),
        (igcd, f64, "Igcd"),
        (vbs, f64, "Vbs"),
        (vgs, f64, "Vgs"),
        (vds, f64, "Vds"),
        (cgg, f64, "Cggb"),
        (cgs, f64, "Cgsb"),
        (cgd, f64, "Cgdb"),
        (cbg, f64, "Cbgb"),
        (cbd, f64, "Cbdb"),
        (cbs, f64, "Cbsb"),
        (cdg, f64, "Cdgb"),
        (cdd, f64, "Cddb"),
        (cds, f64, "Cdsb"),
        (csg, f64, "Csgb"),
        (csd, f64, "Csdb"),
        (css, f64, "Cssb"),
        (cgb, f64, "Cgbb"),
        (cdb, f64, "Cdbb"),
        (csb, f64, "Csbb"),
        (cbb, f64, "Cbbb"),
        (capbd, f64, "Capbd"),
        (capbs, f64, "Capbs"),
        (qg, f64, "Qgate"),
        (qb, f64, "Qbulk"),
        (qd, f64, "Qdrain"),
        (qs, f64, "Qsource"),
        (qinv, f64, "Qinversion"),
        (qdef, f64, "Qdef"),
        (gcrg, f64, "Gcrg"),
        (gtau, f64, "Gtau"),
    ]
}

paramstruct! {
    Bsim4Model,
    "BSIM4 Model Parameters", [
        (cvchargemod, usize, "Capacitance Charge model selector"),
        (capmod, usize, "Capacitance model selector"),
        (diomod, usize, "Diode IV model selector"),
        (rdsmod, usize, "Bias-dependent S/D resistance model selector"),
        (trnqsmod, usize, "Transient NQS model selector"),
        (acnqsmod, usize, "AC NQS model selector"),
        (mobmod, usize, "Mobility model selector"),
        (rbodymod, usize, "Distributed body R model selector"),
        (rgatemod, usize, "Gate R model selector"),
        (permod, usize, "Pd and Ps model selector"),
        (geomod, usize, "Geometry dependent parasitics model selector"),
        (fnoimod, usize, "Flicker noise model selector"),
        (tnoimod, usize, "Thermal noise model selector"),
        (mtrlmod, usize, "parameter for non-silicon substrate or metal gate selector"),
        (mtrlcompatmod, usize, "New Material Mod backward compatibility selector"),
        (igcmod, usize, "Gate-to-channel Ig model selector"),
        (igbmod, usize, "Gate-to-body Ig model selector"),
        (tempmod, usize, "Temperature model selector"),
        (gidlmod, usize, "parameter for GIDL selector"), /* v4.7 New GIDL/GISL */
        (paramchk, usize, "Model parameter checking selector"),
        (binunit, usize, "Bin  unit  selector"),
        (version, f64, "parameter for model version"),
        (eot, f64, "Equivalent gate oxide thickness in meters"),
        (vddeot, f64, "Voltage for extraction of Equivalent gate oxide thickness"),
        (tempeot, f64, " Temperature for extraction of EOT"),
        (leffeot, f64, " Effective length for extraction of EOT"),
        (weffeot, f64, "Effective width for extraction of EOT"),
        (ados, f64, "Charge centroid parameter"),
        (bdos, f64, "Charge centroid parameter"),
        (toxe, f64, "Electrical gate oxide thickness in meters"),
        (toxp, f64, "Physical gate oxide thickness in meters"),
        (toxm, f64, "Gate oxide thickness at which parameters are extracted"),
        (toxref, f64, "Target tox value"),
        (dtox, f64, "Defined as (toxe - toxp) "),
        (epsrox, f64, "Dielectric constant of the gate oxide relative to vacuum"),
        (cdsc, f64, "Drain/Source and channel coupling capacitance"),
        (cdscb, f64, "Body-bias dependence of cdsc"),
        (cdscd, f64, "Drain-bias dependence of cdsc"),
        (cit, f64, "Interface state capacitance"),
        (nfactor, f64, "Subthreshold swing Coefficient"),
        (xj, f64, "Junction depth in meters"),
        (vsat, f64, "Saturation velocity at tnom"),
        (at, f64, "Temperature coefficient of vsat"),
        (a0, f64, "Non-uniform depletion width effect coefficient."),
        (ags, f64, "Gate bias  coefficient of Abulk."),
        (a1, f64, "Non-saturation effect coefficient"),
        (a2, f64, "Non-saturation effect coefficient"),
        (keta, f64, "Body-bias coefficient of non-uniform depletion width effect."),
        (phig, f64, "Work function of gate"),
        (epsrgate, f64, "Dielectric constant of gate relative to vacuum"),
        (easub, f64, "Electron affinity of substrate"),
        (epsrsub, f64, "Dielectric constant of substrate relative to vacuum"),
        (ni0sub, f64, "Intrinsic carrier concentration of substrate at 300.15K"),
        (bg0sub, f64, "Band-gap of substrate at T=0K"),
        (tbgasub, f64, "First parameter of band-gap change due to temperature"),
        (tbgbsub, f64, "Second parameter of band-gap change due to temperature"),
        (nsub, f64, "Substrate doping concentration"),
        (ndep, f64, "Channel doping concentration at the depletion edge"),
        (nsd, f64, "S/D doping concentration"),
        (phin, f64, "Adjusting parameter for surface potential due to non-uniform vertical doping"),
        (ngate, f64, "Poly-gate doping concentration"),
        (gamma1, f64, "Vth body coefficient"),
        (gamma2, f64, "Vth body coefficient"),
        (vbx, f64, "Vth transition body Voltage"),
        (vbm, f64, "Maximum body voltage"),
        (xt, f64, "Doping depth"),
        (k1, f64, "Bulk effect coefficient 1"),
        (kt1, f64, "Temperature coefficient of Vth"),
        (kt1l, f64, "Temperature coefficient of Vth"),
        (kt2, f64, "Body-coefficient of kt1"),
        (k2, f64, "Bulk effect coefficient 2"),
        (k3, f64, "Narrow width effect coefficient"),
        (k3b, f64, "Body effect coefficient of k3"),
        (w0, f64, "Narrow width effect parameter"),
        (dvtp0, f64, "First parameter for Vth shift due to pocket"),
        (dvtp1, f64, "Second parameter for Vth shift due to pocket"),
        (dvtp2, f64, "3rd parameter for Vth shift due to pocket"),
        (dvtp3, f64, "4th parameter for Vth shift due to pocket"),
        (dvtp4, f64, "5th parameter for Vth shift due to pocket"),
        (dvtp5, f64, "6th parameter for Vth shift due to pocket"),
        (lpe0, f64, "Equivalent length of pocket region at zero bias"),
        (lpeb, f64, "Equivalent length of pocket region accounting for body bias"),
        (dvt0, f64, "Short channel effect coeff. 0"),
        (dvt1, f64, "Short channel effect coeff. 1"),
        (dvt2, f64, "Short channel effect coeff. 2"),
        (dvt0w, f64, "Narrow Width coeff. 0"),
        (dvt1w, f64, "Narrow Width effect coeff. 1"),
        (dvt2w, f64, "Narrow Width effect coeff. 2"),
        (drout, f64, "DIBL coefficient of output resistance"),
        (dsub, f64, "DIBL coefficient in the subthreshold region"),
        (vth0, f64,"Threshold voltage"),
        (vtho, f64,"Threshold voltage"),
        (ua, f64, "Linear gate dependence of mobility"),
        (ua1, f64, "Temperature coefficient of ua"),
        (ub, f64, "Quadratic gate dependence of mobility"),
        (ub1, f64, "Temperature coefficient of ub"),
        (uc, f64, "Body-bias dependence of mobility"),
        (uc1, f64, "Temperature coefficient of uc"),
        (ud, f64, "Coulomb scattering factor of mobility"),
        (ud1, f64, "Temperature coefficient of ud"),
        (up, f64, "Channel length linear factor of mobility"),
        (lp, f64, "Channel length exponential factor of mobility"),
        (u0, f64, "Low-field mobility at Tnom"),
        (eu, f64, "Mobility exponent"),
        (ucs, f64, "Colombic scattering exponent"),
        (ute, f64, "Temperature coefficient of mobility"),
        (ucste, f64,"Temperature coefficient of colombic mobility"),
        (voff, f64, "Threshold voltage offset"),
        (minv, f64, "Fitting parameter for moderate inversion in Vgsteff"),
        (minvcv, f64, "Fitting parameter for moderate inversion in Vgsteffcv"),
        (voffl, f64, "Length dependence parameter for Vth offset"),
        (voffcvl, f64, "Length dependence parameter for Vth offset in CV"),
        (tnom, f64, "Parameter measurement temperature"),
        (cgso, f64, "Gate-source overlap capacitance per width"),
        (cgdo, f64, "Gate-drain overlap capacitance per width"),
        (cgbo, f64, "Gate-bulk overlap capacitance per length"),
        (xpart, f64, "Channel charge partitioning"),
        (delta, f64, "Effective Vds parameter"),
        (rsh, f64, "Source-drain sheet resistance"),
        (rdsw, f64, "Source-drain resistance per width"),
        (rdswmin, f64, "Source-drain resistance per width at high Vg"),
        (rsw, f64, "Source resistance per width"),
        (rdw, f64, "Drain resistance per width"),
        (rdwmin, f64, "Drain resistance per width at high Vg"),
        (rswmin, f64, "Source resistance per width at high Vg"),
        (prwg, f64, "Gate-bias effect on parasitic resistance "),
        (prwb, f64, "Body-effect on parasitic resistance "),
        (prt, f64, "Temperature coefficient of parasitic resistance "),
        (eta0, f64, "Subthreshold region DIBL coefficient"),
        (etab, f64, "Subthreshold region DIBL coefficient"),
        (pclm, f64, "Channel length modulation Coefficient"),
        (pdiblc1, f64, "Drain-induced barrier lowering coefficient"),
        (pdiblc2, f64, "Drain-induced barrier lowering coefficient"),
        (pdiblcb, f64, "Body-effect on drain-induced barrier lowering"),
        (fprout, f64, "Rout degradation coefficient for pocket devices"),
        (pdits, f64, "Coefficient for drain-induced Vth shifts"),
        (pditsl, f64, "Length dependence of drain-induced Vth shifts"),
        (pditsd, f64, "Vds dependence of drain-induced Vth shifts"),
        (pscbe1, f64, "Substrate current body-effect coefficient"),
        (pscbe2, f64, "Substrate current body-effect coefficient"),
        (pvag, f64, "Gate dependence of output resistance parameter"),
        (jss, f64, "Bottom source junction reverse saturation current density"),
        (jsws, f64, "Isolation edge sidewall source junction reverse saturation current density"),
        (jswgs, f64, "Gate edge source junction reverse saturation current density"),
        (pbs, f64, "Source junction built-in potential"),
        (njs, f64, "Source junction emission coefficient"),
        (xtis, f64, "Source junction current temperature exponent"),
        (mjs, f64, "Source bottom junction capacitance grading coefficient"),
        (pbsws, f64, "Source sidewall junction capacitance built in potential"),
        (mjsws, f64, "Source sidewall junction capacitance grading coefficient"),
        (pbswgs, f64, "Source (gate side) sidewall junction capacitance built in potential"),
        (mjswgs, f64, "Source (gate side) sidewall junction capacitance grading coefficient"),
        (cjs, f64, "Source bottom junction capacitance per unit area"),
        (cjsws, f64, "Source sidewall junction capacitance per unit periphery"),
        (cjswgs, f64, "Source (gate side) sidewall junction capacitance per unit width"),
        (jsd, f64, "Bottom drain junction reverse saturation current density"),
        (jswd, f64, "Isolation edge sidewall drain junction reverse saturation current density"),
        (jswgd, f64, "Gate edge drain junction reverse saturation current density"),
        (pbd, f64, "Drain junction built-in potential"),
        (njd, f64, "Drain junction emission coefficient"),
        (xtid, f64, "Drainjunction current temperature exponent"),
        (mjd, f64, "Drain bottom junction capacitance grading coefficient"),
        (pbswd, f64, "Drain sidewall junction capacitance built in potential"),
        (mjswd, f64, "Drain sidewall junction capacitance grading coefficient"),
        (pbswgd, f64, "Drain (gate side) sidewall junction capacitance built in potential"),
        (mjswgd, f64, "Drain (gate side) sidewall junction capacitance grading coefficient"),
        (cjd, f64, "Drain bottom junction capacitance per unit area"),
        (cjswd, f64, "Drain sidewall junction capacitance per unit periphery"),
        (cjswgd, f64, "Drain (gate side) sidewall junction capacitance per unit width"),
        (vfbcv, f64, "Flat Band Voltage parameter for capmod=0 only"),
        (vfb, f64, "Flat Band Voltage"),
        (tpb, f64, "Temperature coefficient of pb"),
        (tcj, f64, "Temperature coefficient of cj"),
        (tpbsw, f64, "Temperature coefficient of pbsw"),
        (tcjsw, f64, "Temperature coefficient of cjsw"),
        (tpbswg, f64, "Temperature coefficient of pbswg"),
        (tcjswg, f64, "Temperature coefficient of cjswg"),
        (acde, f64, "Exponential coefficient for finite charge thickness"),
        (moin, f64, "Coefficient for gate-bias dependent surface potential"),
        (noff, f64, "C-V turn-on/off parameter"),
        (voffcv, f64, "C-V lateral-shift parameter"),
        (dmcg, f64, "Distance of Mid-Contact to Gate edge"),
        (dmci, f64, "Distance of Mid-Contact to Isolation"),
        (dmdg, f64, "Distance of Mid-Diffusion to Gate edge"),
        (dmcgt, f64, "Distance of Mid-Contact to Gate edge in Test structures"),
        (xgw, f64, "Distance from gate contact center to device edge"),
        (xgl, f64, "Variation in Ldrawn"),
        (rshg, f64, "Gate sheet resistance"),
        (ngcon, f64, "Number of gate contacts"),
        (xrcrg1, f64, "First fitting parameter the bias-dependent Rg"),
        (xrcrg2, f64, "Second fitting parameter the bias-dependent Rg"),
        (lambda, f64, " Velocity overshoot parameter"),
        (vtl, f64, " thermal velocity"),
        (lc, f64, " back scattering parameter"),
        (xn, f64, " back scattering parameter"),
        (vfbsdoff, f64, "S/D flatband voltage offset"),
        (tvfbsdoff, f64, "Temperature parameter for vfbsdoff"),
        (tvoff, f64, "Temperature parameter for voff"),
        (tnfactor, f64, "Temperature parameter for nfactor"), /* v4.7 Tanvir*/
        (teta0, f64, "Temperature parameter for eta0"), /* v4.7 Tanvir*/
        (tvoffcv, f64, "Temperature parameter for tvoffcv"), /* v4.7 Tanvir*/
        (lintnoi, f64, "lint offset for noise calculation"),
        (lint, f64, "Length reduction parameter"),
        (ll, f64, "Length reduction parameter"),
        (llc, f64, "Length reduction parameter for CV"),
        (lln, f64, "Length reduction parameter"),
        (lw, f64, "Length reduction parameter"),
        (lwc, f64, "Length reduction parameter for CV"),
        (lwn, f64, "Length reduction parameter"),
        (lwl, f64, "Length reduction parameter"),
        (lwlc, f64, "Length reduction parameter for CV"),
        (lmin, f64, "Minimum length for the model"),
        (lmax, f64, "Maximum length for the model"),
        (wr, f64, "Width dependence of rds"),
        (wint, f64, "Width reduction parameter"),
        (dwg, f64, "Width reduction parameter"),
        (dwb, f64, "Width reduction parameter"),
        (wl, f64, "Width reduction parameter"),
        (wlc, f64, "Width reduction parameter for CV"),
        (wln, f64, "Width reduction parameter"),
        (ww, f64, "Width reduction parameter"),
        (wwc, f64, "Width reduction parameter for CV"),
        (wwn, f64, "Width reduction parameter"),
        (wwl, f64, "Width reduction parameter"),
        (wwlc, f64, "Width reduction parameter for CV"),
        (wmin, f64, "Minimum width for the model"),
        (wmax, f64, "Maximum width for the model"),
        (b0, f64, "Abulk narrow width parameter"),
        (b1, f64, "Abulk narrow width parameter"),
        (cgsl, f64, "New C-V model parameter"),
        (cgdl, f64, "New C-V model parameter"),
        (ckappas, f64, "S/G overlap C-V parameter "),
        (ckappad, f64, "D/G overlap C-V parameter"),
        (cf, f64, "Fringe capacitance parameter"),
        (clc, f64, "Vdsat parameter for C-V model"),
        (cle, f64, "Vdsat parameter for C-V model"),
        (dwc, f64, "Delta W for C-V model"),
        (dlc, f64, "Delta L for C-V model"),
        (xw, f64, "W offset for channel width due to mask/etch effect"),
        (xl, f64, "L offset for channel length due to mask/etch effect"),
        (dlcig, f64, "Delta L for Ig model"),
        (dlcigd, f64, "Delta L for Ig model drain side"),
        (dwj, f64, "Delta W for S/D junctions"),
        (alpha0, f64, "substrate current model parameter"),
        (alpha1, f64, "substrate current model parameter"),
        (beta0, f64, "substrate current model parameter"),
        (agidl, f64, "Pre-exponential constant for GIDL"),
        (bgidl, f64, "Exponential constant for GIDL"),
        (cgidl, f64, "Parameter for body-bias dependence of GIDL"),
        (rgidl, f64, "GIDL vg parameter"), /* v4.7 New GIDL/GISL */
        (kgidl, f64, "GIDL vb parameter"), /* v4.7 New GIDL/GISL */
        (fgidl, f64, "GIDL vb parameter"), /* v4.7 New GIDL/GISL */
        (egidl, f64, "Fitting parameter for Bandbending"),
        (agisl, f64, "Pre-exponential constant for GISL"),
        (bgisl, f64, "Exponential constant for GISL"),
        (cgisl, f64, "Parameter for body-bias dependence of GISL"),
        (rgisl, f64, "GISL vg parameter"), /* v4.7 New GIDL/GISL */
        (kgisl, f64, "GISL vb parameter"), /* v4.7 New GIDL/GISL */
        (fgisl, f64, "GISL vb parameter"), /* v4.7 New GIDL/GISL */
        (egisl, f64, "Fitting parameter for Bandbending"),
        (aigc, f64, "Parameter for Igc"),
        (bigc, f64, "Parameter for Igc"),
        (cigc, f64, "Parameter for Igc"),
        (aigsd, f64, "Parameter for Igs,d"),
        (bigsd, f64, "Parameter for Igs,d"),
        (cigsd, f64, "Parameter for Igs,d"),
        (aigs, f64, "Parameter for Igs"),
        (bigs, f64, "Parameter for Igs"),
        (cigs, f64, "Parameter for Igs"),
        (aigd, f64, "Parameter for Igd"),
        (bigd, f64, "Parameter for Igd"),
        (cigd, f64, "Parameter for Igd"),
        (aigbacc, f64, "Parameter for Igb"),
        (bigbacc, f64, "Parameter for Igb"),
        (cigbacc, f64, "Parameter for Igb"),
        (aigbinv, f64, "Parameter for Igb"),
        (bigbinv, f64, "Parameter for Igb"),
        (cigbinv, f64, "Parameter for Igb"),
        (nigc, f64, "Parameter for Igc slope"),
        (nigbinv, f64, "Parameter for Igbinv slope"),
        (nigbacc, f64, "Parameter for Igbacc slope"),
        (ntox, f64, "Exponent for Tox ratio"),
        (eigbinv, f64, "Parameter for the Si bandgap for Igbinv"),
        (pigcd, f64, "Parameter for Igc partition"),
        (poxedge, f64, "Factor for the gate edge Tox"),
        (ijthdfwd, f64, "Forward drain diode forward limiting current"),
        (ijthsfwd, f64, "Forward source diode forward limiting current"),
        (ijthdrev, f64, "Reverse drain diode forward limiting current"),
        (ijthsrev, f64, "Reverse source diode forward limiting current"),
        (xjbvd, f64, "Fitting parameter for drain diode breakdown current"),
        (xjbvs, f64, "Fitting parameter for source diode breakdown current"),
        (bvd, f64, "Drain diode breakdown voltage"),
        (bvs, f64, "Source diode breakdown voltage"),
        (jtss, f64, "Source bottom trap-assisted saturation current density"),
        (jtsd, f64, "Drain bottom trap-assisted saturation current density"),
        (jtssws, f64, "Source STI sidewall trap-assisted saturation current density"),
        (jtsswd, f64, "Drain STI sidewall trap-assisted saturation current density"),
        (jtsswgs, f64, "Source gate-edge sidewall trap-assisted saturation current density"),
        (jtsswgd, f64, "Drain gate-edge sidewall trap-assisted saturation current density"),
        (jtweff, f64, "TAT current width dependance"),
        (njts, f64, "Non-ideality factor for bottom junction"),
        (njtssw, f64, "Non-ideality factor for STI sidewall junction"),
        (njtsswg, f64, "Non-ideality factor for gate-edge sidewall junction"),
        (njtsd, f64, "Non-ideality factor for bottom junction drain side"),
        (njtsswd, f64, "Non-ideality factor for STI sidewall junction drain side"),
        (njtsswgd, f64, "Non-ideality factor for gate-edge sidewall junction drain side"),
        (xtss, f64, "Power dependence of JTSS on temperature"),
        (xtsd, f64, "Power dependence of JTSD on temperature"),
        (xtssws, f64, "Power dependence of JTSSWS on temperature"),
        (xtsswd, f64, "Power dependence of JTSSWD on temperature"),
        (xtsswgs, f64, "Power dependence of JTSSWGS on temperature"),
        (xtsswgd, f64, "Power dependence of JTSSWGD on temperature"),
        (tnjts, f64, "Temperature coefficient for NJTS"),
        (tnjtssw, f64, "Temperature coefficient for NJTSSW"),
        (tnjtsswg, f64, "Temperature coefficient for NJTSSWG"),
        (tnjtsd, f64, "Temperature coefficient for NJTSD"),
        (tnjtsswd, f64, "Temperature coefficient for NJTSSWD"),
        (tnjtsswgd, f64, "Temperature coefficient for NJTSSWGD"),
        (vtss, f64, "Source bottom trap-assisted voltage dependent parameter"),
        (vtsd, f64, "Drain bottom trap-assisted voltage dependent parameter"),
        (vtssws, f64, "Source STI sidewall trap-assisted voltage dependent parameter"),
        (vtsswd, f64, "Drain STI sidewall trap-assisted voltage dependent parameter"),
        (vtsswgs, f64, "Source gate-edge sidewall trap-assisted voltage dependent parameter"),
        (vtsswgd, f64, "Drain gate-edge sidewall trap-assisted voltage dependent parameter"),
        (gbmin, f64, "Minimum body conductance"),
        (rbdb, f64, "Resistance between bNode and dbNode"),
        (rbpb, f64, "Resistance between bNodePrime and bNode"),
        (rbsb, f64, "Resistance between bNode and sbNode"),
        (rbps, f64, "Resistance between bNodePrime and sbNode"),
        (rbpd, f64, "Resistance between bNodePrime and bNode"),
        (rbps0, f64, "Body resistance RBPS scaling"),
        (rbpsl, f64, "Body resistance RBPS L scaling"),
        (rbpsw, f64, "Body resistance RBPS W scaling"),
        (rbpsnf, f64, "Body resistance RBPS NF scaling"),
        (rbpd0, f64, "Body resistance RBPD scaling"),
        (rbpdl, f64, "Body resistance RBPD L scaling"),
        (rbpdw, f64, "Body resistance RBPD W scaling"),
        (rbpdnf, f64, "Body resistance RBPD NF scaling"),
        (rbpbx0, f64, "Body resistance RBPBX  scaling"),
        (rbpbxl, f64, "Body resistance RBPBX L scaling"),
        (rbpbxw, f64, "Body resistance RBPBX W scaling"),
        (rbpbxnf, f64, "Body resistance RBPBX NF scaling"),
        (rbpby0, f64, "Body resistance RBPBY  scaling"),
        (rbpbyl, f64, "Body resistance RBPBY L scaling"),
        (rbpbyw, f64, "Body resistance RBPBY W scaling"),
        (rbpbynf, f64, "Body resistance RBPBY NF scaling"),
        (rbsbx0, f64, "Body resistance RBSBX  scaling"),
        (rbsby0, f64, "Body resistance RBSBY  scaling"),
        (rbdbx0, f64, "Body resistance RBDBX  scaling"),
        (rbdby0, f64, "Body resistance RBDBY  scaling"),
        (rbsdbxl, f64, "Body resistance RBSDBX L scaling"),
        (rbsdbxw, f64, "Body resistance RBSDBX W scaling"),
        (rbsdbxnf, f64, "Body resistance RBSDBX NF scaling"),
        (rbsdbyl, f64, "Body resistance RBSDBY L scaling"),
        (rbsdbyw, f64, "Body resistance RBSDBY W scaling"),
        (rbsdbynf, f64, "Body resistance RBSDBY NF scaling"),
        (lcdsc, f64, "Length dependence of cdsc"),
        (lcdscb, f64, "Length dependence of cdscb"),
        (lcdscd, f64, "Length dependence of cdscd"),
        (lcit, f64, "Length dependence of cit"),
        (lnfactor, f64, "Length dependence of nfactor"),
        (lxj, f64, "Length dependence of xj"),
        (lvsat, f64, "Length dependence of vsat"),
        (lat, f64, "Length dependence of at"),
        (la0, f64, "Length dependence of a0"),
        (lags, f64, "Length dependence of ags"),
        (la1, f64, "Length dependence of a1"),
        (la2, f64, "Length dependence of a2"),
        (lketa, f64, "Length dependence of keta"),
        (lnsub, f64, "Length dependence of nsub"),
        (lndep, f64, "Length dependence of ndep"),
        (lnsd, f64, "Length dependence of nsd"),
        (lphin, f64, "Length dependence of phin"),
        (lngate, f64, "Length dependence of ngate"),
        (lgamma1, f64, "Length dependence of gamma1"),
        (lgamma2, f64, "Length dependence of gamma2"),
        (lvbx, f64, "Length dependence of vbx"),
        (lvbm, f64, "Length dependence of vbm"),
        (lxt, f64, "Length dependence of xt"),
        (lk1, f64, "Length dependence of k1"),
        (lkt1, f64, "Length dependence of kt1"),
        (lkt1l, f64, "Length dependence of kt1l"),
        (lkt2, f64, "Length dependence of kt2"),
        (lk2, f64, "Length dependence of k2"),
        (lk3, f64, "Length dependence of k3"),
        (lk3b, f64, "Length dependence of k3b"),
        (lw0, f64, "Length dependence of w0"),
        (ldvtp0, f64, "Length dependence of dvtp0"),
        (ldvtp1, f64, "Length dependence of dvtp1"),
        (ldvtp2, f64, "Length dependence of dvtp2"),
        (ldvtp3, f64, "Length dependence of dvtp3"),
        (ldvtp4, f64, "Length dependence of dvtp4"),
        (ldvtp5, f64, "Length dependence of dvtp5"),
        (llpe0, f64, "Length dependence of lpe0"),
        (llpeb, f64, "Length dependence of lpeb"),
        (ldvt0, f64, "Length dependence of dvt0"),
        (ldvt1, f64, "Length dependence of dvt1"),
        (ldvt2, f64, "Length dependence of dvt2"),
        (ldvt0w, f64, "Length dependence of dvt0w"),
        (ldvt1w, f64, "Length dependence of dvt1w"),
        (ldvt2w, f64, "Length dependence of dvt2w"),
        (ldrout, f64, "Length dependence of drout"),
        (ldsub, f64, "Length dependence of dsub"),
        (lvth0, f64,"Length dependence of vto"),
        (lvtho, f64,"Length dependence of vto"),
        (lua, f64, "Length dependence of ua"),
        (lua1, f64, "Length dependence of ua1"),
        (lub, f64, "Length dependence of ub"),
        (lub1, f64, "Length dependence of ub1"),
        (luc, f64, "Length dependence of uc"),
        (luc1, f64, "Length dependence of uc1"),
        (lud, f64, "Length dependence of ud"),
        (lud1, f64, "Length dependence of ud1"),
        (lup, f64, "Length dependence of up"),
        (llp, f64, "Length dependence of lp"),
        (lu0, f64, "Length dependence of u0"),
        (lute, f64, "Length dependence of ute"),
        (lucste, f64, "Length dependence of ucste"),
        (lvoff, f64, "Length dependence of voff"),
        (lminv, f64, "Length dependence of minv"),
        (lminvcv, f64, "Length dependence of minvcv"),
        (ldelta, f64, "Length dependence of delta"),
        (lrdsw, f64, "Length dependence of rdsw "),
        (lrsw, f64, "Length dependence of rsw"),
        (lrdw, f64, "Length dependence of rdw"),
        (lprwg, f64, "Length dependence of prwg "),
        (lprwb, f64, "Length dependence of prwb "),
        (lprt, f64, "Length dependence of prt "),
        (leta0, f64, "Length dependence of eta0"),
        (letab, f64, "Length dependence of etab"),
        (lpclm, f64, "Length dependence of pclm"),
        (lpdiblc1, f64, "Length dependence of pdiblc1"),
        (lpdiblc2, f64, "Length dependence of pdiblc2"),
        (lpdiblcb, f64, "Length dependence of pdiblcb"),
        (lfprout, f64, "Length dependence of pdiblcb"),
        (lpdits, f64, "Length dependence of pdits"),
        (lpditsd, f64, "Length dependence of pditsd"),
        (lpscbe1, f64, "Length dependence of pscbe1"),
        (lpscbe2, f64, "Length dependence of pscbe2"),
        (lpvag, f64, "Length dependence of pvag"),
        (lwr, f64, "Length dependence of wr"),
        (ldwg, f64, "Length dependence of dwg"),
        (ldwb, f64, "Length dependence of dwb"),
        (lb0, f64, "Length dependence of b0"),
        (lb1, f64, "Length dependence of b1"),
        (lcgsl, f64, "Length dependence of cgsl"),
        (lcgdl, f64, "Length dependence of cgdl"),
        (lckappas, f64, "Length dependence of ckappas"),
        (lckappad, f64, "Length dependence of ckappad"),
        (lcf, f64, "Length dependence of cf"),
        (lclc, f64, "Length dependence of clc"),
        (lcle, f64, "Length dependence of cle"),
        (lalpha0, f64, "Length dependence of alpha0"),
        (lalpha1, f64, "Length dependence of alpha1"),
        (lbeta0, f64, "Length dependence of beta0"),
        (lagidl, f64, "Length dependence of agidl"),
        (lbgidl, f64, "Length dependence of bgidl"),
        (lcgidl, f64, "Length dependence of cgidl"),
        (lrgidl, f64, "Length dependence of rgidl"), /* v4.7 New GIDL/GISL */
        (lkgidl, f64, "Length dependence of kgidl"), /* v4.7 New GIDL/GISL */
        (lfgidl, f64, "Length dependence of fgidl"), /* v4.7 New GIDL/GISL */
        (legidl, f64, "Length dependence of egidl"),
        (lagisl, f64, "Length dependence of agisl"),
        (lbgisl, f64, "Length dependence of bgisl"),
        (lcgisl, f64, "Length dependence of cgisl"),
        (lrgisl, f64, "Length dependence of rgisl"), /* v4.7 New GIDL/GISL */
        (lkgisl, f64, "Length dependence of kgisl"), /* v4.7 New GIDL/GISL */
        (lfgisl, f64, "Length dependence of fgisl"), /* v4.7 New GIDL/GISL */
        (legisl, f64, "Length dependence of egisl"),
        (laigc, f64, "Length dependence of aigc"),
        (lbigc, f64, "Length dependence of bigc"),
        (lcigc, f64, "Length dependence of cigc"),
        (laigsd, f64, "Length dependence of aigsd"),
        (lbigsd, f64, "Length dependence of bigsd"),
        (lcigsd, f64, "Length dependence of cigsd"),
        (laigs, f64, "Length dependence of aigs"),
        (lbigs, f64, "Length dependence of bigs"),
        (lcigs, f64, "Length dependence of cigs"),
        (laigd, f64, "Length dependence of aigd"),
        (lbigd, f64, "Length dependence of bigd"),
        (lcigd, f64, "Length dependence of cigd"),
        (laigbacc, f64, "Length dependence of aigbacc"),
        (lbigbacc, f64, "Length dependence of bigbacc"),
        (lcigbacc, f64, "Length dependence of cigbacc"),
        (laigbinv, f64, "Length dependence of aigbinv"),
        (lbigbinv, f64, "Length dependence of bigbinv"),
        (lcigbinv, f64, "Length dependence of cigbinv"),
        (lnigc, f64, "Length dependence of nigc"),
        (lnigbinv, f64, "Length dependence of nigbinv"),
        (lnigbacc, f64, "Length dependence of nigbacc"),
        (lntox, f64, "Length dependence of ntox"),
        (leigbinv, f64, "Length dependence for eigbinv"),
        (lpigcd, f64, "Length dependence for pigcd"),
        (lpoxedge, f64, "Length dependence for poxedge"),
        (lvfbcv, f64, "Length dependence of vfbcv"),
        (lvfb, f64, "Length dependence of vfb"),
        (lacde, f64, "Length dependence of acde"),
        (lmoin, f64, "Length dependence of moin"),
        (lnoff, f64, "Length dependence of noff"),
        (lvoffcv, f64, "Length dependence of voffcv"),
        (lxrcrg1, f64, "Length dependence of xrcrg1"),
        (lxrcrg2, f64, "Length dependence of xrcrg2"),
        (llambda, f64, "Length dependence of lambda"),
        (lvtl, f64, " Length dependence of vtl"),
        (lxn, f64, " Length dependence of xn"),
        (leu, f64, " Length dependence of eu"),
        (lucs, f64, "Length dependence of lucs"),
        (lvfbsdoff, f64, "Length dependence of vfbsdoff"),
        (ltvfbsdoff, f64, "Length dependence of tvfbsdoff"),
        (ltvoff, f64, "Length dependence of tvoff"),
        (ltnfactor, f64, "Length dependence of tnfactor"), /* v4.7 Tanvir*/
        (lteta0, f64, "Length dependence of teta0"), /* v4.7 Tanvir*/
        (ltvoffcv, f64, "Length dependence of tvoffcv"), /* v4.7 Tanvir*/
        (wcdsc, f64, "Width dependence of cdsc"),
        (wcdscb, f64, "Width dependence of cdscb"),
        (wcdscd, f64, "Width dependence of cdscd"),
        (wcit, f64, "Width dependence of cit"),
        (wnfactor, f64, "Width dependence of nfactor"),
        (wxj, f64, "Width dependence of xj"),
        (wvsat, f64, "Width dependence of vsat"),
        (wat, f64, "Width dependence of at"),
        (wa0, f64, "Width dependence of a0"),
        (wags, f64, "Width dependence of ags"),
        (wa1, f64, "Width dependence of a1"),
        (wa2, f64, "Width dependence of a2"),
        (wketa, f64, "Width dependence of keta"),
        (wnsub, f64, "Width dependence of nsub"),
        (wndep, f64, "Width dependence of ndep"),
        (wnsd, f64, "Width dependence of nsd"),
        (wphin, f64, "Width dependence of phin"),
        (wngate, f64, "Width dependence of ngate"),
        (wgamma1, f64, "Width dependence of gamma1"),
        (wgamma2, f64, "Width dependence of gamma2"),
        (wvbx, f64, "Width dependence of vbx"),
        (wvbm, f64, "Width dependence of vbm"),
        (wxt, f64, "Width dependence of xt"),
        (wk1, f64, "Width dependence of k1"),
        (wkt1, f64, "Width dependence of kt1"),
        (wkt1l, f64, "Width dependence of kt1l"),
        (wkt2, f64, "Width dependence of kt2"),
        (wk2, f64, "Width dependence of k2"),
        (wk3, f64, "Width dependence of k3"),
        (wk3b, f64, "Width dependence of k3b"),
        (ww0, f64, "Width dependence of w0"),
        (wdvtp0, f64, "Width dependence of dvtp0"),
        (wdvtp1, f64, "Width dependence of dvtp1"),
        (wdvtp2, f64, "Width dependence of dvtp2"),
        (wdvtp3, f64, "Width dependence of dvtp3"),
        (wdvtp4, f64, "Width dependence of dvtp4"),
        (wdvtp5, f64, "Width dependence of dvtp5"),
        (wlpe0, f64, "Width dependence of lpe0"),
        (wlpeb, f64, "Width dependence of lpeb"),
        (wdvt0, f64, "Width dependence of dvt0"),
        (wdvt1, f64, "Width dependence of dvt1"),
        (wdvt2, f64, "Width dependence of dvt2"),
        (wdvt0w, f64, "Width dependence of dvt0w"),
        (wdvt1w, f64, "Width dependence of dvt1w"),
        (wdvt2w, f64, "Width dependence of dvt2w"),
        (wdrout, f64, "Width dependence of drout"),
        (wdsub, f64, "Width dependence of dsub"),
        (wvth0, f64,"Width dependence of vto"),
        (wvtho, f64,"Width dependence of vto"),
        (wua, f64, "Width dependence of ua"),
        (wua1, f64, "Width dependence of ua1"),
        (wub, f64, "Width dependence of ub"),
        (wub1, f64, "Width dependence of ub1"),
        (wuc, f64, "Width dependence of uc"),
        (wuc1, f64, "Width dependence of uc1"),
        (wud, f64, "Width dependence of ud"),
        (wud1, f64, "Width dependence of ud1"),
        (wup, f64, "Width dependence of up"),
        (wlp, f64, "Width dependence of lp"),
        (wu0, f64, "Width dependence of u0"),
        (wute, f64, "Width dependence of ute"),
        (wucste, f64, "Width dependence of ucste"),
        (wvoff, f64, "Width dependence of voff"),
        (wminv, f64, "Width dependence of minv"),
        (wminvcv, f64, "Width dependence of minvcv"),
        (wdelta, f64, "Width dependence of delta"),
        (wrdsw, f64, "Width dependence of rdsw "),
        (wrsw, f64, "Width dependence of rsw"),
        (wrdw, f64, "Width dependence of rdw"),
        (wprwg, f64, "Width dependence of prwg "),
        (wprwb, f64, "Width dependence of prwb "),
        (wprt, f64, "Width dependence of prt"),
        (weta0, f64, "Width dependence of eta0"),
        (wetab, f64, "Width dependence of etab"),
        (wpclm, f64, "Width dependence of pclm"),
        (wpdiblc1, f64, "Width dependence of pdiblc1"),
        (wpdiblc2, f64, "Width dependence of pdiblc2"),
        (wpdiblcb, f64, "Width dependence of pdiblcb"),
        (wfprout, f64, "Width dependence of pdiblcb"),
        (wpdits, f64, "Width dependence of pdits"),
        (wpditsd, f64, "Width dependence of pditsd"),
        (wpscbe1, f64, "Width dependence of pscbe1"),
        (wpscbe2, f64, "Width dependence of pscbe2"),
        (wpvag, f64, "Width dependence of pvag"),
        (wwr, f64, "Width dependence of wr"),
        (wdwg, f64, "Width dependence of dwg"),
        (wdwb, f64, "Width dependence of dwb"),
        (wb0, f64, "Width dependence of b0"),
        (wb1, f64, "Width dependence of b1"),
        (wcgsl, f64, "Width dependence of cgsl"),
        (wcgdl, f64, "Width dependence of cgdl"),
        (wckappas, f64, "Width dependence of ckappas"),
        (wckappad, f64, "Width dependence of ckappad"),
        (wcf, f64, "Width dependence of cf"),
        (wclc, f64, "Width dependence of clc"),
        (wcle, f64, "Width dependence of cle"),
        (walpha0, f64, "Width dependence of alpha0"),
        (walpha1, f64, "Width dependence of alpha1"),
        (wbeta0, f64, "Width dependence of beta0"),
        (wagidl, f64, "Width dependence of agidl"),
        (wbgidl, f64, "Width dependence of bgidl"),
        (wcgidl, f64, "Width dependence of cgidl"),
        (wrgidl, f64, "Width dependence of rgidl"), /* v4.7 New GIDL/GISL */
        (wkgidl, f64, "Width dependence of kgidl"), /* v4.7 New GIDL/GISL */
        (wfgidl, f64, "Width dependence of fgidl"), /* v4.7 New GIDL/GISL */
        (wegidl, f64, "Width dependence of egidl"),
        (wagisl, f64, "Width dependence of agisl"),
        (wbgisl, f64, "Width dependence of bgisl"),
        (wcgisl, f64, "Width dependence of cgisl"),
        (wrgisl, f64, "Width dependence of rgisl"), /* v4.7 New GIDL/GISL */
        (wkgisl, f64, "Width dependence of kgisl"), /* v4.7 New GIDL/GISL */
        (wfgisl, f64, "Width dependence of fgisl"), /* v4.7 New GIDL/GISL */
        (wegisl, f64, "Width dependence of egisl"),
        (waigc, f64, "Width dependence of aigc"),
        (wbigc, f64, "Width dependence of bigc"),
        (wcigc, f64, "Width dependence of cigc"),
        (waigsd, f64, "Width dependence of aigsd"),
        (wbigsd, f64, "Width dependence of bigsd"),
        (wcigsd, f64, "Width dependence of cigsd"),
        (waigs, f64, "Width dependence of aigs"),
        (wbigs, f64, "Width dependence of bigs"),
        (wcigs, f64, "Width dependence of cigs"),
        (waigd, f64, "Width dependence of aigd"),
        (wbigd, f64, "Width dependence of bigd"),
        (wcigd, f64, "Width dependence of cigd"),
        (waigbacc, f64, "Width dependence of aigbacc"),
        (wbigbacc, f64, "Width dependence of bigbacc"),
        (wcigbacc, f64, "Width dependence of cigbacc"),
        (waigbinv, f64, "Width dependence of aigbinv"),
        (wbigbinv, f64, "Width dependence of bigbinv"),
        (wcigbinv, f64, "Width dependence of cigbinv"),
        (wnigc, f64, "Width dependence of nigc"),
        (wnigbinv, f64, "Width dependence of nigbinv"),
        (wnigbacc, f64, "Width dependence of nigbacc"),
        (wntox, f64, "Width dependence of ntox"),
        (weigbinv, f64, "Width dependence for eigbinv"),
        (wpigcd, f64, "Width dependence for pigcd"),
        (wpoxedge, f64, "Width dependence for poxedge"),
        (wvfbcv, f64, "Width dependence of vfbcv"),
        (wvfb, f64, "Width dependence of vfb"),
        (wacde, f64, "Width dependence of acde"),
        (wmoin, f64, "Width dependence of moin"),
        (wnoff, f64, "Width dependence of noff"),
        (wvoffcv, f64, "Width dependence of voffcv"),
        (wxrcrg1, f64, "Width dependence of xrcrg1"),
        (wxrcrg2, f64, "Width dependence of xrcrg2"),
        (wlambda, f64, "Width dependence of lambda"),
        (wvtl, f64, "Width dependence of vtl"),
        (wxn, f64, "Width dependence of xn"),
        (weu, f64, "Width dependence of eu"),
        (wucs, f64, "Width dependence of ucs"),
        (wvfbsdoff, f64, "Width dependence of vfbsdoff"),
        (wtvfbsdoff, f64, "Width dependence of tvfbsdoff"),
        (wtvoff, f64, "Width dependence of tvoff"),
        (wtnfactor, f64, "Width dependence of tnfactor"), /* v4.7 Tanvir*/
        (wteta0, f64, "Width dependence of teta0"), /* v4.7 Tanvir*/
        (wtvoffcv, f64, "Width dependence of tvoffcv"), /* v4.7 Tanvir*/
        (pcdsc, f64, "Cross-term dependence of cdsc"),
        (pcdscb, f64, "Cross-term dependence of cdscb"),
        (pcdscd, f64, "Cross-term dependence of cdscd"),
        (pcit, f64, "Cross-term dependence of cit"),
        (pnfactor, f64, "Cross-term dependence of nfactor"),
        (pxj, f64, "Cross-term dependence of xj"),
        (pvsat, f64, "Cross-term dependence of vsat"),
        (pat, f64, "Cross-term dependence of at"),
        (pa0, f64, "Cross-term dependence of a0"),
        (pags, f64, "Cross-term dependence of ags"),
        (pa1, f64, "Cross-term dependence of a1"),
        (pa2, f64, "Cross-term dependence of a2"),
        (pketa, f64, "Cross-term dependence of keta"),
        (pnsub, f64, "Cross-term dependence of nsub"),
        (pndep, f64, "Cross-term dependence of ndep"),
        (pnsd, f64, "Cross-term dependence of nsd"),
        (pphin, f64, "Cross-term dependence of phin"),
        (pngate, f64, "Cross-term dependence of ngate"),
        (pgamma1, f64, "Cross-term dependence of gamma1"),
        (pgamma2, f64, "Cross-term dependence of gamma2"),
        (pvbx, f64, "Cross-term dependence of vbx"),
        (pvbm, f64, "Cross-term dependence of vbm"),
        (pxt, f64, "Cross-term dependence of xt"),
        (pk1, f64, "Cross-term dependence of k1"),
        (pkt1, f64, "Cross-term dependence of kt1"),
        (pkt1l, f64, "Cross-term dependence of kt1l"),
        (pkt2, f64, "Cross-term dependence of kt2"),
        (pk2, f64, "Cross-term dependence of k2"),
        (pk3, f64, "Cross-term dependence of k3"),
        (pk3b, f64, "Cross-term dependence of k3b"),
        (pw0, f64, "Cross-term dependence of w0"),
        (pdvtp0, f64, "Cross-term dependence of dvtp0"),
        (pdvtp1, f64, "Cross-term dependence of dvtp1"),
        (pdvtp2, f64, "Cross-term dependence of dvtp2"),
        (pdvtp3, f64, "Cross-term dependence of dvtp3"),
        (pdvtp4, f64, "Cross-term dependence of dvtp4"),
        (pdvtp5, f64, "Cross-term dependence of dvtp5"),
        (plpe0, f64, "Cross-term dependence of lpe0"),
        (plpeb, f64, "Cross-term dependence of lpeb"),
        (pdvt0, f64, "Cross-term dependence of dvt0"),
        (pdvt1, f64, "Cross-term dependence of dvt1"),
        (pdvt2, f64, "Cross-term dependence of dvt2"),
        (pdvt0w, f64, "Cross-term dependence of dvt0w"),
        (pdvt1w, f64, "Cross-term dependence of dvt1w"),
        (pdvt2w, f64, "Cross-term dependence of dvt2w"),
        (pdrout, f64, "Cross-term dependence of drout"),
        (pdsub, f64, "Cross-term dependence of dsub"),
        (pvth0, f64,"Cross-term dependence of vto"),
        (pvtho, f64,"Cross-term dependence of vto"),
        (pua, f64, "Cross-term dependence of ua"),
        (pua1, f64, "Cross-term dependence of ua1"),
        (r#pub, f64, "Cross-term dependence of ub"), // Note: r# allows use of the keyword `pub`
        (pub1, f64, "Cross-term dependence of ub1"),
        (puc, f64, "Cross-term dependence of uc"),
        (puc1, f64, "Cross-term dependence of uc1"),
        (pud, f64, "Cross-term dependence of ud"),
        (pud1, f64, "Cross-term dependence of ud1"),
        (pup, f64, "Cross-term dependence of up"),
        (plp, f64, "Cross-term dependence of lp"),
        (pu0, f64, "Cross-term dependence of u0"),
        (pute, f64, "Cross-term dependence of ute"),
        (pucste, f64, "Cross-term dependence of ucste"),
        (pvoff, f64, "Cross-term dependence of voff"),
        (pminv, f64, "Cross-term dependence of minv"),
        (pminvcv, f64, "Cross-term dependence of minvcv"),
        (pdelta, f64, "Cross-term dependence of delta"),
        (prdsw, f64, "Cross-term dependence of rdsw "),
        (prsw, f64, "Cross-term dependence of rsw"),
        (prdw, f64, "Cross-term dependence of rdw"),
        (pprwg, f64, "Cross-term dependence of prwg "),
        (pprwb, f64, "Cross-term dependence of prwb "),
        (pprt, f64, "Cross-term dependence of prt "),
        (peta0, f64, "Cross-term dependence of eta0"),
        (petab, f64, "Cross-term dependence of etab"),
        (ppclm, f64, "Cross-term dependence of pclm"),
        (ppdiblc1, f64, "Cross-term dependence of pdiblc1"),
        (ppdiblc2, f64, "Cross-term dependence of pdiblc2"),
        (ppdiblcb, f64, "Cross-term dependence of pdiblcb"),
        (pfprout, f64, "Cross-term dependence of pdiblcb"),
        (ppdits, f64, "Cross-term dependence of pdits"),
        (ppditsd, f64, "Cross-term dependence of pditsd"),
        (ppscbe1, f64, "Cross-term dependence of pscbe1"),
        (ppscbe2, f64, "Cross-term dependence of pscbe2"),
        (ppvag, f64, "Cross-term dependence of pvag"),
        (pwr, f64, "Cross-term dependence of wr"),
        (pdwg, f64, "Cross-term dependence of dwg"),
        (pdwb, f64, "Cross-term dependence of dwb"),
        (pb0, f64, "Cross-term dependence of b0"),
        (pb1, f64, "Cross-term dependence of b1"),
        (pcgsl, f64, "Cross-term dependence of cgsl"),
        (pcgdl, f64, "Cross-term dependence of cgdl"),
        (pckappas, f64, "Cross-term dependence of ckappas"),
        (pckappad, f64, "Cross-term dependence of ckappad"),
        (pcf, f64, "Cross-term dependence of cf"),
        (pclc, f64, "Cross-term dependence of clc"),
        (pcle, f64, "Cross-term dependence of cle"),
        (palpha0, f64, "Cross-term dependence of alpha0"),
        (palpha1, f64, "Cross-term dependence of alpha1"),
        (pbeta0, f64, "Cross-term dependence of beta0"),
        (pagidl, f64, "Cross-term dependence of agidl"),
        (pbgidl, f64, "Cross-term dependence of bgidl"),
        (pcgidl, f64, "Cross-term dependence of cgidl"),
        (prgidl, f64, "Cross-term dependence of rgidl"), /* v4.7 New GIDL/GISL */
        (pkgidl, f64, "Cross-term dependence of kgidl"), /* v4.7 New GIDL/GISL */
        (pfgidl, f64, "Cross-term dependence of fgidl"), /* v4.7 New GIDL/GISL */
        (pegidl, f64, "Cross-term dependence of egidl"),
        (pagisl, f64, "Cross-term dependence of agisl"),
        (pbgisl, f64, "Cross-term dependence of bgisl"),
        (pcgisl, f64, "Cross-term dependence of cgisl"),
        (pegisl, f64, "Cross-term dependence of egisl"),
        (prgisl, f64, "Cross-term dependence of rgisl"), /* v4.7 New GIDL/GISL */
        (pkgisl, f64, "Cross-term dependence of kgisl"), /* v4.7 New GIDL/GISL */
        (pfgisl, f64, "Cross-term dependence of fgisl"), /* v4.7 New GIDL/GISL */
        (paigc, f64, "Cross-term dependence of aigc"),
        (pbigc, f64, "Cross-term dependence of bigc"),
        (pcigc, f64, "Cross-term dependence of cigc"),
        (paigsd, f64, "Cross-term dependence of aigsd"),
        (pbigsd, f64, "Cross-term dependence of bigsd"),
        (pcigsd, f64, "Cross-term dependence of cigsd"),
        (paigs, f64, "Cross-term dependence of aigs"),
        (pbigs, f64, "Cross-term dependence of bigs"),
        (pcigs, f64, "Cross-term dependence of cigs"),
        (paigd, f64, "Cross-term dependence of aigd"),
        (pbigd, f64, "Cross-term dependence of bigd"),
        (pcigd, f64, "Cross-term dependence of cigd"),
        (paigbacc, f64, "Cross-term dependence of aigbacc"),
        (pbigbacc, f64, "Cross-term dependence of bigbacc"),
        (pcigbacc, f64, "Cross-term dependence of cigbacc"),
        (paigbinv, f64, "Cross-term dependence of aigbinv"),
        (pbigbinv, f64, "Cross-term dependence of bigbinv"),
        (pcigbinv, f64, "Cross-term dependence of cigbinv"),
        (pnigc, f64, "Cross-term dependence of nigc"),
        (pnigbinv, f64, "Cross-term dependence of nigbinv"),
        (pnigbacc, f64, "Cross-term dependence of nigbacc"),
        (pntox, f64, "Cross-term dependence of ntox"),
        (peigbinv, f64, "Cross-term dependence for eigbinv"),
        (ppigcd, f64, "Cross-term dependence for pigcd"),
        (ppoxedge, f64, "Cross-term dependence for poxedge"),
        (pvfbcv, f64, "Cross-term dependence of vfbcv"),
        (pvfb, f64, "Cross-term dependence of vfb"),
        (pacde, f64, "Cross-term dependence of acde"),
        (pmoin, f64, "Cross-term dependence of moin"),
        (pnoff, f64, "Cross-term dependence of noff"),
        (pvoffcv, f64, "Cross-term dependence of voffcv"),
        (pxrcrg1, f64, "Cross-term dependence of xrcrg1"),
        (pxrcrg2, f64, "Cross-term dependence of xrcrg2"),
        (plambda, f64, "Cross-term dependence of lambda"),
        (pvtl, f64, "Cross-term dependence of vtl"),
        (pxn, f64, "Cross-term dependence of xn"),
        (peu, f64, "Cross-term dependence of eu"),
        (pucs, f64, "Cross-term dependence of ucs"),
        (pvfbsdoff, f64, "Cross-term dependence of vfbsdoff"),
        (ptvfbsdoff, f64, "Cross-term dependence of tvfbsdoff"),
        (ptvoff, f64, "Cross-term dependence of tvoff"),
        (ptnfactor, f64, "Cross-term dependence of tnfactor"), /* v4.7 Tanvir*/
        (pteta0, f64, "Cross-term dependence of teta0"), /* v4.7 Tanvir*/
        (ptvoffcv, f64, "Cross-term dependence of tvoffcv"), /* v4.7 Tanvir*/
        /* stress effect*/
        (saref, f64, "Reference distance between OD edge to poly of one side"),
        (sbref, f64, "Reference distance between OD edge to poly of the other side"),
        (wlod, f64, "Width parameter for stress effect"),
        (ku0, f64, "Mobility degradation/enhancement coefficient for LOD"),
        (kvsat, f64, "Saturation velocity degradation/enhancement parameter for LOD"),
        (kvth0, f64, "Threshold degradation/enhancement parameter for LOD"),
        (tku0, f64, "Temperature coefficient of KU0"),
        (llodku0, f64, "Length parameter for u0 LOD effect"),
        (wlodku0, f64, "Width parameter for u0 LOD effect"),
        (llodvth, f64, "Length parameter for vth LOD effect"),
        (wlodvth, f64, "Width parameter for vth LOD effect"),
        (lku0, f64, "Length dependence of ku0"),
        (wku0, f64, "Width dependence of ku0"),
        (pku0, f64, "Cross-term dependence of ku0"),
        (lkvth0, f64, "Length dependence of kvth0"),
        (wkvth0, f64, "Width dependence of kvth0"),
        (pkvth0, f64, "Cross-term dependence of kvth0"),
        (stk2, f64, "K2 shift factor related to stress effect on vth"),
        (lodk2, f64, "K2 shift modification factor for stress effect"),
        (steta0, f64, "eta0 shift factor related to stress effect on vth"),
        (lodeta0, f64, "eta0 shift modification factor for stress effect"),
        /* Well Proximity Effect */
        (web, f64, "Coefficient for SCB"),
        (wec, f64, "Coefficient for SCC"),
        (kvth0we, f64, "Threshold shift factor for well proximity effect"),
        (k2we, f64, " K2 shift factor for well proximity effect "),
        (ku0we, f64, " Mobility degradation factor for well proximity effect "),
        (scref, f64, " Reference distance to calculate SCA, SCB and SCC"),
        (wpemod, f64, " Flag for WPE model (WPEMOD=1 to activate this model) "),
        (lkvth0we, f64, "Length dependence of kvth0we"),
        (lk2we, f64, " Length dependence of k2we "),
        (lku0we, f64, " Length dependence of ku0we "),
        (wkvth0we, f64, "Width dependence of kvth0we"),
        (wk2we, f64, " Width dependence of k2we "),
        (wku0we, f64, " Width dependence of ku0we "),
        (pkvth0we, f64, "Cross-term dependence of kvth0we"),
        (pk2we, f64, " Cross-term dependence of k2we "),
        (pku0we, f64, " Cross-term dependence of ku0we "),
        //
        (noia, f64, "Flicker noise parameter"),
        (noib, f64, "Flicker noise parameter"),
        (noic, f64, "Flicker noise parameter"),
        (tnoia, f64, "Thermal noise parameter"),
        (tnoib, f64, "Thermal noise parameter"),
        (tnoic, f64, "Thermal noise parameter"),
        (rnoia, f64, "Thermal noise coefficient"),
        (rnoib, f64, "Thermal noise coefficient"),
        (rnoic, f64, "Thermal noise coefficient"),
        (ntnoi, f64, "Thermal noise parameter"),
        (em, f64, "Flicker noise parameter"),
        (ef, f64, "Flicker noise frequency exponent"),
        (af, f64, "Flicker noise exponent"),
        (kf, f64, "Flicker noise coefficient"),
        //
        (nmos, bool, "Flag to indicate NMOS"),
        (pmos, bool, "Flag to indicate PMOS"),
    ]
}
